Repository pokt-network/pocket-core, pull requests merged in 2019-03, with the labels that each got.

#239 Added ip and port flags to service start script
  cmd.sh
Labels: infrastructure, mvp

#241 Issue #240
  cmd.sh
Labels: infrastructure, mvp

#250 patched bug, returned proper error code
  dispatch/dispatch.go
  node/whitelist.go
  rpc/relay/dispatch.go
  util/http.go
Labels: bug, enhancement

#262 Issue #261
  const/filename.go
Labels: bug

#264 Issue #263
  db/peers.go
  rpc/relay/live.go
  service/service.go
  tests/integration/fixtures/report.json
  tests/unit/service_test.go
Labels: enhancement

#269 Issue #286
  cmd.sh
Labels: bug

#291 Added Dockerfile
  Dockerfile
Labels: enhancement, infrastructure
