Repository pokt-network/pocket-core, pull requests merged in 2019-04, with the labels that each got.

#299 Fixes integration bug from relay test closes #298
  plugin/rpc/rpc.go
  tests/integration/developer_test.go
  tests/integration/dispatch_test.go
  tests/integration/service_test.go
  tests/unit/db_test.go
  util/url.go
Labels: bug, enhancement

#319 Changed default for requestTimeout flag to 0
  cmd.sh
Labels: enhancement, infrastructure

#328 Issue #326
  db/peers.go
Labels: bug

#331 Added `--ip` and `--port` flags to readme
  README.md
Labels: documentation
