Repository pokt-network/pocket-core, pull requests merged in 2019-02, with the labels that each got.

#150 fixed gets in cmd dispatch message node and session modules, repaired…
  tests/rpc/dispatch_test.go
  tests/rpc/reference_test.go
  tests/rpc/relay_test.go
  tests/rpc/report_test.go
Labels: bug, enhancement

#161 Added circleci integration for building and running the tests
  .circleci/config.yml
Labels: enhancement

#166 Shutdown if chains file problem
  node/config.go
Labels: enhancement

#169 Added CircleCI Badge to README
  README.md
Labels: documentation

#192 Issue #189
  Dockerfile
Labels: enhancement, infrastructure

#205 Improved Dockerfile to add initialization via ENTRYPOINT / added entr…
  .gitignore
  Dockerfile
  entrypoint.sh
Labels: enhancement, infrastructure, mvp

#207 moved register and unregister api functionality to relay port
  node/live.go
  rpc/client/routes.go
  rpc/relay/flags.go
  rpc/relay/live.go
  rpc/relay/routes.go
Labels: enhancement, mvp

#212 Exposed port 8081
  .gitignore
  Dockerfile
Labels: bug, mvp

#223 Updated the readme to fix #199 MVP
  README.md
Labels: documentation

#225 Issue #224
  cmd.sh
Labels: infrastructure, mvp

#227 changed dispatch serve response for easier parsing
  dispatch/dispatch.go
Labels: enhancement

#235 issue-#233A
  README.md
  config/config.go
  const/ip.go
  crypto/util.go
  db/peers.go
  dispatch/dispatch.go
  node/config.go
  node/self.go
  node/whitelist.go
  types/set.go
Labels: bug
