Repository pokt-network/pocket-core, pull requests merged in 2020-03, with the labels that each got.

#725 stop double sign on invalid operation, avoid consensus break
  x/nodes/keeper/slash.go
  x/nodes/keeper/slash_test.go
Labels: bug, high priority

#736 update app version to 0.2.1
  app/app.go
  doc/changelog.md
Labels: documentation, enhancement

#738 Fix changelog versioning.
  doc/changelog.md
Labels: bug, documentation

#741 Fixes issue #740
  .circleci/config.yml
Labels: bug
