Repository pokt-network/pocket-core, pull requests merged in 2023-12, with the labels that each got.

#1580 [v0.11 feature] Per-chain Relays To Token Multiplier
  app/tx_test.go
  codec/codec.go
  go.mod
  go.sum
  types/param.go
  types/utils.go
  x/gov/module.go
  x/gov/types/expectedKeepers.go
  x/nodes/keeper/abci.go
  x/nodes/keeper/common_test.go
  x/nodes/keeper/keeper.go
  x/nodes/keeper/params.go
  x/nodes/keeper/reward.go
  x/nodes/keeper/reward_test.go
  x/nodes/keeper/slash_test.go
  x/nodes/module.go
  x/nodes/types/params.go
  x/pocketcore/keeper/nodes.go
  x/pocketcore/keeper/proof.go
  x/pocketcore/types/expectedKeepers.go
  x/pocketcore/types/service_test.go
Labels: large, waiting-for-review

#1582 feat: enforce max chains during new session
  .circleci/config.yml
  codec/codec.go
  go.mod
  go.sum
  x/pocketcore/keeper/claim.go
  x/pocketcore/types/errors.go
  x/pocketcore/types/expectedKeepers.go
  x/pocketcore/types/service.go
  x/pocketcore/types/service_test.go
  x/pocketcore/types/session.go
  x/pocketcore/types/session_test.go
Labels: enhancement, large, waiting-for-review

#1585 Allow an AppMsgStake tx to change the address of a staked app
  app/app.go
  app/cmd/cli/app.go
  app/cmd/cli/txUtil.go
  baseapp/baseapp.go
  codec/codec.go
  x/apps/handler.go
  x/apps/keeper/appStateChanges.go
  x/apps/keeper/appStateChanges_test.go
  x/apps/keeper/appUtil.go
  x/apps/keeper/common_test.go
  x/apps/types/msg.go
  x/auth/ante.go
  x/auth/keeper/keeper.go
  x/auth/types/expectedKeepers.go
Labels: large, waiting-for-review

#1588 Do not call `node.GetChains()` if node is nil
  x/pocketcore/types/session.go
Labels: small, waiting-for-review

#1587 Upgrade Go version to 1.21
  .circleci/config.yml
  .github/workflows/Dockerfile
  CONTRIBUTING.md
  README.md
  go.mod
  go.sum
Labels: small, waiting-for-review

#1581 [v0.11 feature] Built-in Reward Share
  app/cmd/cli/node.go
  app/cmd/cli/txUtil.go
  app/cmd/rpc/rpc_test.go
  codec/codec.go
  go.mod
  go.sum
  proto/x/nodes/msg.proto
  proto/x/nodes/nodes.proto
  types/config.go
  x/auth/types/txbuilder.go
  x/nodes/genesis_test.go
  x/nodes/handler.go
  x/nodes/keeper/abci_test.go
  x/nodes/keeper/common_test.go
  x/nodes/keeper/keeper.go
  x/nodes/keeper/params.go
  x/nodes/keeper/reward.go
  x/nodes/keeper/reward_test.go
  x/nodes/keeper/valStateChanges.go
  x/nodes/keeper/valStateChanges_test.go
  x/nodes/keeper/validator.go
  x/nodes/keeper/validator_test.go
  x/nodes/types/errors.go
  x/nodes/types/expectedKeepers.go
  x/nodes/types/msg.go
  x/nodes/types/msg.pb.go
  x/nodes/types/msg_test.go
  x/nodes/types/nodes.pb.go
  x/nodes/types/params_test.go
  x/nodes/types/util.go
  x/nodes/types/util_test.go
  x/nodes/types/validator.go
  x/nodes/types/validator_legacy.go
  x/nodes/types/validator_test.go
  x/pocketcore/keeper/claim.go
  x/pocketcore/types/expectedKeepers.go
  x/pocketcore/types/service_test.go
Labels: large, waiting-for-review
