Repository pokt-network/pocket-core, pull requests merged in 2023-07, with the labels that each got.

#1566 Revert Mainnet genesis file changes from #1535
  app/genesis.go
Labels: small, waiting-for-review

#1560 Update default session sync allowance
  types/config.go
Labels: small, waiting-for-review

#1565 Add snapshot docs
  README.md
  doc/guides/snapshot.md
Labels: small, docs, waiting-for-review

#1568 Change default config file values
  types/config.go
Labels: small, waiting-for-review

#1569 Testnet docs updated
  README.md
  doc/guides/testnet.md
Labels: small, docs, waiting-for-review

#1570 Update TestNet documentation
  doc/guides/testnet.md
Labels: medium, docs, waiting-for-review

#1572 Add a reference to Pocket Pruner
  README.md
  doc/guides/pruner.md
Labels: small, docs, waiting-for-review
