Repository pokt-network/pocket-core, pull requests merged in 2024-01, with the labels that each got.

#1590 Update AppVersion to BETA-0.11.0
  app/app.go
Labels: consensus breaking, small, waiting-for-review

#1591 Sort RewardDelegators when marshaling a validator
  proto/x/nodes/nodes.proto
  x/nodes/keeper/validator_test.go
  x/nodes/types/nodes.pb.go
Labels: bug, medium, waiting-for-review

#1593 [Docs] Update main `README` w/ links to `Docker` images
  README.md
Labels: documentation, small, docs, waiting-for-review

#1592 Update AppVersion to BETA-0.11.1
  app/app.go
Labels: small, waiting-for-review

#1594 Add mainnet seeds to README
  README.md
Labels: small, docs, waiting-for-review

#1595 Update AppVersion to RC-0.11.1
  app/app.go
Labels: small, waiting-for-review
